# Generated by Django 2.2.6 on 2020-03-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosquad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
