# Generated by Django 2.2.6 on 2020-03-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosquad', '0002_auto_20200306_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='flatno',
            field=models.IntegerField(default=False),
        ),
    ]
